### ISSUE TITLE
グローバル部分をLOOPさせる方法を

### ISSUE THREAD

**Issue by tk-a** [akihiro1977/category_swiper#1]
最近よくニュースアプリにありがちな、
グローバル部分をフリックさせられて、両端をLOOPさせる方法を、
<a href="https://github.com/akihiro1977">i-section.netの小柳 様</a>より教わりました！

以下がその内容となります。<br />
------------------------------------------------------------------<br />
> 一番右端まで、もしくは、一番左端のコンテンツを、
> 右端の場合は右に。左端の場合は左へフリックさせた際に、
> トップへ戻るような、無限loop的な動きをつけようとしてみたのですが、、
> どうしてもできず…もしこちらを無限loopのようにする方法をご存じならば
> お教え頂きたくご連絡をさせて頂きました。

当該コードの最後の方に前／次のコンテンツへの移動メソッドがあります。

prev: function(){
if (category_swiper.categoryIndex>0){
var $t = $("[data-cs-categories] a:eq("+(category_swiper.categoryIndex-1)+")");
$t.trigger("click");
}
},
next: function(){
var $t = $("[data-cs-categories] a:eq("+(category_swiper.categoryIndex+1)+")");
if ($t.length) $t.trigger("click");
}

この部分を変更するのが一番早いのではないかと思います。
こんな感じでしょうか（動作未確認）

prev: function(){
if (category_swiper.categoryIndex>0){
var $t = $("[data-cs-categories] a:eq("+(category_swiper.categoryIndex-1)+")");
$t.trigger("click");
} else {
// 前のコンテンツがないので最後に移動
$("[data-cs-categories] a:last").trigger("click");
}
},
next: function(){
var $t = $("[data-cs-categories] a:eq("+(category_swiper.categoryIndex+1)+")");
if ($t.length){
$t.trigger("click");
} else {
// 次のコンテンツがないので最初に移動
$("[data-cs-categories] a:first").trigger("click");
}
}

とても参考になりました！

**Comment by akihiro1977** [comment]
お役に立てれば幸いです！
プログラム楽しんで下さい〜
